root: true
env:
  browser: true
  es2021: true
  node: true
extends:
  - "plugin:markdown/recommended"
  - "plugin:vue/vue3-essential"
  - "plugin:@typescript-eslint/recommended"
  - "standard-with-typescript"
  - "prettier"
parser: "vue-eslint-parser"
parserOptions:
  parser: "@typescript-eslint/parser"
  ecmaVersion: "latest"
  ecmaFeatures:
    jsx: true
    impliedStrict: true
  sourceType: "module"
  project:
    [
      "./tsconfig.json",
      "./packages/**/tsconfig.json",
      "./plugins/**/tsconfig.json",
    ]
  extraFileExtensions: [".vue", ".md"]
plugins:
  - "@typescript-eslint"
rules:
  indent: ["error", 2, { SwitchCase: 1 }]
  linebreak-style: ["warn", "unix"]
  quotes: ["error", "single"]
  semi: ["error", "never"]
  "@typescript-eslint/no-non-null-assertion": 0
  "@typescript-eslint/explicit-function-return-type": 0
  "@typescript-eslint/strict-boolean-expressions": 0
  "@typescript-eslint/no-namespace": 0
  "@typescript-eslint/method-signature-style": 0
  "@typescript-eslint/return-await": 0
  "@typescript-eslint/no-var-requires": 0
  "vue/max-attributes-per-line":
    ["warn", { singleline: { max: 3 }, multiline: { max: 1 } }]
