packages:
  - "external/*"
  - "external/*/external/*"
  - "external/*/external/*/packages/*"
  - "external/*/external/*/packages/@*/*"
  - "external/*/packages/*"
  - "external/*/packages/@*/*"
  - "external/*/plugins/*"
  - "external/satori/adapters/*"
  - "external/koishi/plugins/*"
  - "external/koishi/plugins/adapter/*"
  - "external/koishi/plugins/common/*"
  - "external/koishi/plugins/database/*"
  - "packages/*"
  - "packages/@*/*"
  - "plugins/*"
  - "plugins/@*/*"
